import { AdhkarCategory, DhikrItem } from '@/types/models';

export const adhkarCategories: AdhkarCategory[] = [
  { id: 'morning', titleAr: 'أذكار الصباح', titleEn: 'Morning Adhkar', icon: 'sun' },
  { id: 'evening', titleAr: 'أذكار المساء', titleEn: 'Evening Adhkar', icon: 'moon' },
  { id: 'sleep', titleAr: 'أذكار النوم', titleEn: 'Before Sleep', icon: 'bed' },
  { id: 'after_prayer', titleAr: 'أذكار بعد الصلاة', titleEn: 'After Prayer', icon: 'clock' },
  { id: 'mosque', titleAr: 'أذكار المسجد', titleEn: 'Mosque Adhkar', icon: 'home' },
  { id: 'supplications', titleAr: 'أدعية مأثورة', titleEn: 'Prophetic Supplications', icon: 'book' },
  { id: 'quranic', titleAr: 'أدعية قرآنية', titleEn: 'Quranic Supplications', icon: 'book-open' },
  { id: 'travel', titleAr: 'دعاء السفر', titleEn: 'Travel Supplication', icon: 'navigation' },
  { id: 'ruqyah', titleAr: 'الرقية الشرعية', titleEn: 'Ruqyah', icon: 'shield' },
];

export const adhkarItems: DhikrItem[] = [
  {
    id: 'morning-1',
    categoryId: 'morning',
    textAr:
      'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ ﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾.',
    textEn: 'Recite Ayat al-Kursi in the morning.',
    source: 'حصن المسلم (75) - صحيح',
    repeat: 1,
  },
  {
    id: 'morning-2',
    categoryId: 'morning',
    textAr:
      'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ﴿قُلْ هُوَ اللَّهُ أَحَدٌ﴾، ﴿قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ﴾، ﴿قُلْ أَعُوذُ بِرَبِّ النَّاسِ﴾.',
    textEn: 'Recite Al-Ikhlas, Al-Falaq, and An-Nas.',
    source: 'حصن المسلم (76)',
    repeat: 3,
  },
  {
    id: 'morning-3',
    categoryId: 'morning',
    textAr:
      'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ.',
    textEn: 'Sayyid al-Istighfar.',
    source: 'حصن المسلم (79) - صحيح البخاري',
    repeat: 1,
  },
  {
    id: 'morning-4',
    categoryId: 'morning',
    textAr: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ.',
    textEn: 'In the name of Allah with whose name nothing harms...',
    source: 'حصن المسلم (86)',
    repeat: 3,
  },
  {
    id: 'morning-5',
    categoryId: 'morning',
    textAr: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا.',
    textEn: 'I am pleased with Allah as Lord...',
    source: 'حصن المسلم (87)',
    repeat: 3,
  },
  {
    id: 'morning-6',
    categoryId: 'morning',
    textAr: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ.',
    textEn: 'Glory and praise be to Allah.',
    source: 'حصن المسلم (91)',
    repeat: 100,
  },
  {
    id: 'evening-1',
    categoryId: 'evening',
    textAr:
      'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ.',
    textEn: 'We have entered evening and with it all dominion belongs to Allah.',
    source: 'حصن المسلم (77)',
    repeat: 1,
  },
  {
    id: 'evening-2',
    categoryId: 'evening',
    textAr: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ.',
    textEn: 'O Allah, by You we enter evening...',
    source: 'حصن المسلم (78)',
    repeat: 1,
  },
  {
    id: 'evening-3',
    categoryId: 'evening',
    textAr: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ.',
    textEn: 'In the name of Allah with whose name nothing harms...',
    source: 'حصن المسلم (86)',
    repeat: 3,
  },
  {
    id: 'evening-4',
    categoryId: 'evening',
    textAr: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا.',
    textEn: 'I am pleased with Allah as Lord...',
    source: 'حصن المسلم (87)',
    repeat: 3,
  },
  {
    id: 'evening-5',
    categoryId: 'evening',
    textAr: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ.',
    textEn: 'I seek refuge in Allah’s perfect words from the evil of what He created.',
    source: 'حصن المسلم (97)',
    repeat: 3,
  },
  {
    id: 'sleep-1',
    categoryId: 'sleep',
    textAr:
      'يَجْمَعُ كَفَّيْهِ ثُمَّ يَنْفُثُ فِيهِمَا، فَيَقْرَأُ قُلْ هُوَ اللَّهُ أَحَدٌ، وَقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ، وَقُلْ أَعُوذُ بِرَبِّ النَّاسِ، ثُمَّ يَمْسَحُ بِهِمَا جَسَدَهُ.',
    textEn: 'Recite the three Quls, blow into hands, and wipe body.',
    source: 'حصن المسلم (99) - صحيح البخاري',
    repeat: 3,
  },
  {
    id: 'sleep-2',
    categoryId: 'sleep',
    textAr:
      'بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، فَإِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا.',
    textEn: 'In Your name my Lord I lie down and rise up...',
    source: 'حصن المسلم (102)',
    repeat: 1,
  },
  {
    id: 'sleep-3',
    categoryId: 'sleep',
    textAr: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا.',
    textEn: 'In Your name, O Allah, I die and I live.',
    source: 'حصن المسلم (105)',
    repeat: 1,
  },
  {
    id: 'sleep-4',
    categoryId: 'sleep',
    textAr: 'سُبْحَانَ اللَّهِ (33) وَالْحَمْدُ لِلَّهِ (33) وَاللَّهُ أَكْبَرُ (34).',
    textEn: 'SubhanAllah 33, Alhamdulillah 33, Allahu Akbar 34.',
    source: 'حصن المسلم (106)',
    repeat: 1,
  },
  {
    id: 'after-prayer-1',
    categoryId: 'after_prayer',
    textAr: 'أَسْتَغْفِرُ اللَّهَ (ثلاثًا) اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ.',
    textEn: 'Seek forgiveness three times after prayer.',
    source: 'حصن المسلم (66)',
    repeat: 1,
  },
  {
    id: 'after-prayer-2',
    categoryId: 'after_prayer',
    textAr: 'سُبْحَانَ اللَّهِ',
    textEn: 'SubhanAllah',
    source: 'صحيح مسلم',
    repeat: 33,
  },
  {
    id: 'after-prayer-3',
    categoryId: 'after_prayer',
    textAr: 'الْحَمْدُ لِلَّهِ',
    textEn: 'Alhamdulillah',
    source: 'صحيح مسلم',
    repeat: 33,
  },
  {
    id: 'after-prayer-4',
    categoryId: 'after_prayer',
    textAr: 'اللَّهُ أَكْبَرُ',
    textEn: 'Allahu Akbar',
    source: 'صحيح مسلم',
    repeat: 33,
  },
  {
    id: 'after-prayer-5',
    categoryId: 'after_prayer',
    textAr: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ.',
    textEn: 'There is no god but Allah alone...',
    source: 'حصن المسلم (69)',
    repeat: 1,
  },
  {
    id: 'after-prayer-6',
    categoryId: 'after_prayer',
    textAr:
      '﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾ عقب كل صلاة.',
    textEn: 'Recite Ayat al-Kursi after each prayer.',
    source: 'حصن المسلم (71)',
    repeat: 1,
  },
  {
    id: 'mosque-1',
    categoryId: 'mosque',
    textAr:
      'يبدأ برجله اليمنى ويقول: أَعُوذُ بِاللَّهِ الْعَظِيمِ، وَبِوَجْهِهِ الْكَرِيمِ، وَسُلْطَانِهِ الْقَدِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ. بِسْمِ اللَّهِ، وَالصَّلَاةُ وَالسَّلَامُ عَلَى رَسُولِ اللَّهِ، اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ.',
    textEn: 'Supplication when entering the mosque.',
    source: 'حصن المسلم (20)',
    repeat: 1,
  },
  {
    id: 'mosque-2',
    categoryId: 'mosque',
    textAr:
      'يبدأ برجله اليسرى ويقول: بِسْمِ اللَّهِ وَالصَّلَاةُ وَالسَّلَامُ عَلَى رَسُولِ اللَّهِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ، اللَّهُمَّ اعْصِمْنِي مِنَ الشَّيْطَانِ الرَّجِيمِ.',
    textEn: 'Supplication when leaving the mosque.',
    source: 'حصن المسلم (21)',
    repeat: 1,
  },
  {
    id: 'supplication-1',
    categoryId: 'supplications',
    textAr: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ.',
    textEn: 'O Ever-Living, O Sustainer, rectify all my affairs.',
    source: 'حصن المسلم (88)',
    repeat: 1,
  },
  {
    id: 'supplication-2',
    categoryId: 'supplications',
    textAr: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ.',
    textEn: 'O Allah, I ask You for pardon and wellbeing in this life and the next.',
    source: 'حصن المسلم (84)',
    repeat: 1,
  },
  {
    id: 'supplication-3',
    categoryId: 'supplications',
    textAr: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا.',
    textEn: 'O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.',
    source: 'حصن المسلم (95)',
    repeat: 1,
  },
  {
    id: 'quranic-1',
    categoryId: 'quranic',
    textAr: '﴿رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ﴾',
    textEn: 'Our Lord, grant us good in this life and in the Hereafter.',
    source: 'سورة البقرة: 201',
    repeat: 1,
  },
  {
    id: 'quranic-2',
    categoryId: 'quranic',
    textAr: '﴿رَبِّ اشْرَحْ لِي صَدْرِي ۝ وَيَسِّرْ لِي أَمْرِي ۝ وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي ۝ يَفْقَهُوا قَوْلِي﴾',
    textEn: 'My Lord, expand my chest and ease my task for me.',
    source: 'سورة طه: 25-28',
    repeat: 1,
  },
  {
    id: 'quranic-3',
    categoryId: 'quranic',
    textAr: '﴿رَبِّ زِدْنِي عِلْمًا﴾',
    textEn: 'My Lord, increase me in knowledge.',
    source: 'سورة طه: 114',
    repeat: 1,
  },
  {
    id: 'travel-1',
    categoryId: 'travel',
    textAr:
      'اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ. ﴿سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ﴾. اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى، اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ، اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الْأَهْلِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ وَكَآبَةِ الْمَنْظَرِ وَسُوءِ الْمُنْقَلَبِ فِي الْمَالِ وَالْأَهْلِ.',
    textEn: 'Travel supplication.',
    source: 'حصن المسلم (207)',
    repeat: 1,
  },
  {
    id: 'ruqyah-1',
    categoryId: 'ruqyah',
    textAr: 'بِسْمِ اللَّهِ أَرْقِيكَ، مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ، مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنِ حَاسِدٍ، اللَّهُ يَشْفِيكَ، بِسْمِ اللَّهِ أَرْقِيكَ.',
    textEn: 'In the name of Allah, I recite ruqyah for you...',
    source: 'صحيح مسلم',
    repeat: 3,
  },
  {
    id: 'ruqyah-2',
    categoryId: 'ruqyah',
    textAr: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ.',
    textEn: 'I seek refuge in Allah’s perfect words from the evil of what He created.',
    source: 'حصن المسلم (97)',
    repeat: 3,
  },
  {
    id: 'ruqyah-3',
    categoryId: 'ruqyah',
    textAr: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ﴿قُلْ هُوَ اللَّهُ أَحَدٌ﴾، ﴿قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ﴾، ﴿قُلْ أَعُوذُ بِرَبِّ النَّاسِ﴾.',
    textEn: 'Recite Al-Ikhlas, Al-Falaq and An-Nas for ruqyah.',
    source: 'صحيح البخاري',
    repeat: 3,
  },
];
